server:
  port: 9999

spring:
  application:
    name: eureka-server
  profiles:
    active: server2


eureka:
  client:
    #register-with-eureka: true
   # fetch-registry: true
    service-url:
      defaultZone: http://server1:9998/eureka
  instance:
    hostname: server2
    prefer-ip-address: true #优先显示IP


