server:
  port: 9998

spring:
  application:
    name: eureka-server
  profiles:
    active: server1

eureka:
  instance:
    hostname: server1
    prefer-ip-address: true
  client:
   # register-with-eureka: true
    #fetch-registry: true
    service-url:
      defaultZone: http://server2:9999/eureka


#eureka集群是使用相同服务名（eureka-server）进行相互注册搭建而成